WITH RANKED AS (
    SELECT 
        ID,
        ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY) AS R,
        MAX(ID) OVER() AS MAX_ID
    FROM ECOLI_DATA
)

SELECT 
    ID,
    CASE
        WHEN R > MAX_ID * 0.75 THEN 'CRITICAL'
        WHEN R > MAX_ID * 0.5 THEN 'HIGH'
        WHEN R > MAX_ID * 0.25 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM RANKED
ORDER BY ID;