SELECT B.USER_ID, B.NICKNAME
     , B.CITY || ' ' || B.STREET_ADDRESS1 || ' ' ||B.STREET_ADDRESS2 AS 전체주소
     , SUBSTR(TLNO, 1,3)||'-'||SUBSTR(TLNO,4,4)||'-'||SUBSTR(TLNO,8,4) AS 전화번호
FROM USED_GOODS_BOARD A, USED_GOODS_USER B
WHERE A.WRITER_ID = B.USER_ID
GROUP BY B.USER_ID
       , B.NICKNAME
       , B.CITY
       , B.STREET_ADDRESS1
       , B.STREET_ADDRESS2, B.TLNO
HAVING COUNT(A.WRITER_ID) >=3
ORDER BY USER_ID DESC
